@echo off
REM File: kurulum.bat
REM Path: /home/main/public_html/ai.zefre.net/eksi-blocker/kurulum.bat
REM Developer: gneral <gneral@gmail.com>
REM Website: https://ai.zefre.net/
REM R10 Profile: https://www.r10.net/profil/193-gneral.html
REM GitHub: www.github.com/gneral

echo ====================================================
echo Eksi Sozluk Ad Blocker - Windows Kurulum Scripti
echo Gelistirici: gneral
echo ====================================================
echo.

REM Proje bilgilerini tanımla
set PROJECT_NAME=eksi-blocker
set PROJECT_DIR=%~dp0
set PROJECT_ZIP=%PROJECT_DIR%%PROJECT_NAME%.zip

REM İkon dizinini oluştur
if not exist "%PROJECT_DIR%icons" (
    echo Icon dizini olusturuluyor...
    mkdir "%PROJECT_DIR%icons"
) else (
    echo Icon dizini zaten mevcut.
)

REM Base64 ile kodlanmış küçük PNG dosyalarını oluştur
echo Icon dosyalari olusturuluyor...

REM 16x16 icon için basit bir PNG oluştur (base64 ile)
echo iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA1UlEQVQ4T62TzQ3DIAyFcZu1rdRb1Q5AOneAOkAdI+0GdITeoOIWcUhH4BZ+lpAIJQkhv4PDg+fPNhgxsQMA6y3dHswV99d8IkIkUJNS6sZz3QSldDqBjYi7aQCitwPQ91fEvUYQEVAhLJy7MNbPgbHN9B+gEKzgJBhDKGQNsCTd4AMRxFKItkk+YFlC9njsYbcUohCMwhTdAJWdZ0JFxCfiTk0w8n3hR6zQRzRwS2FjLLrpBEw5Y25sUDyP2PlcZCdg0SnZ/j3ObUuvvgEdPQslXu4TS/d5g/EGEEsg8NjkjZgAAAAASUVORK5CYII=> "%PROJECT_DIR%icons\icon16.txt"
certutil -decode "%PROJECT_DIR%icons\icon16.txt" "%PROJECT_DIR%icons\icon16.png" >nul
del "%PROJECT_DIR%icons\icon16.txt"

REM 48x48 icon için basit bir PNG oluştur (base64 ile)
echo iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA9klEQVRoQ+2YQQrDIBBF4zQn8iaF3CAX6A16pN7AW2SZbgwUpEVnNNWZEYaAsOiEyZ83mpl8lD75KJOvP1IAxZEoQBSgAdQJrYBWQCuQWAG1kFpILZRYAbVQYgElVaEC1IGM7/iICrAFTk3zZsLcANbTCZhtOwHGlSkA51YANM1k+n4HUJYngLUf+wDuTQhAboBxHDG/vhvgfhP+xAUYxmlBIa6R7fVRAbzWZQkQ3gMSZVkSVoEQAIlxnpwBSPQAwPv7AARgGBbxsTMNQCXH7ITwHmgaM4zjfD2AXLVH8jZD5ABKoCgABZDwK4E5A3e8A41RHjcnGQDPuRuY7nGzE/+PAAAAAElFTkSuQmCC> "%PROJECT_DIR%icons\icon48.txt"
certutil -decode "%PROJECT_DIR%icons\icon48.txt" "%PROJECT_DIR%icons\icon48.png" >nul
del "%PROJECT_DIR%icons\icon48.txt"

REM 128x128 icon için basit bir PNG oluştur (base64 ile)
echo iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA7UlEQVR4Xu3TQREAAAjDMCYG/DshhODtgyUW9u2+gnoGIm8PABDcAIBgAMHbAxC8PwDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQDBBxC8PQCIrQf9SwD/5i2muwAAAABJRU5ErkJggg==> "%PROJECT_DIR%icons\icon128.txt"
certutil -decode "%PROJECT_DIR%icons\icon128.txt" "%PROJECT_DIR%icons\icon128.png" >nul
del "%PROJECT_DIR%icons\icon128.txt"

echo Iconlar olusturuldu.

REM manifest.json dosyasını oluştur
echo manifest.json dosyasi olusturuluyor...
echo {> "%PROJECT_DIR%manifest.json"
echo   "manifest_version": 3,>> "%PROJECT_DIR%manifest.json"
echo   "name": "Ekşi Sözlük Ad Blocker",>> "%PROJECT_DIR%manifest.json"
echo   "version": "1.0.0",>> "%PROJECT_DIR%manifest.json"
echo   "description": "Ekşi Sözlük için reklam engelleme eklentisi",>> "%PROJECT_DIR%manifest.json"
echo   "author": "gneral",>> "%PROJECT_DIR%manifest.json"
echo   "icons": {>> "%PROJECT_DIR%manifest.json"
echo     "16": "icons/icon16.png",>> "%PROJECT_DIR%manifest.json"
echo     "48": "icons/icon48.png",>> "%PROJECT_DIR%manifest.json"
echo     "128": "icons/icon128.png">> "%PROJECT_DIR%manifest.json"
echo   },>> "%PROJECT_DIR%manifest.json"
echo   "action": {>> "%PROJECT_DIR%manifest.json"
echo     "default_popup": "popup.html",>> "%PROJECT_DIR%manifest.json"
echo     "default_title": "Ekşi Sözlük Ad Blocker">> "%PROJECT_DIR%manifest.json"
echo   },>> "%PROJECT_DIR%manifest.json"
echo   "permissions": [>> "%PROJECT_DIR%manifest.json"
echo     "storage">> "%PROJECT_DIR%manifest.json"
echo   ],>> "%PROJECT_DIR%manifest.json"
echo   "host_permissions": [>> "%PROJECT_DIR%manifest.json"
echo     "*://eksisozluk.com/*",>> "%PROJECT_DIR%manifest.json"
echo     "*://*.eksisozluk.com/*">> "%PROJECT_DIR%manifest.json"
echo   ],>> "%PROJECT_DIR%manifest.json"
echo   "content_scripts": [>> "%PROJECT_DIR%manifest.json"
echo     {>> "%PROJECT_DIR%manifest.json"
echo       "matches": ["*://eksisozluk.com/*", "*://*.eksisozluk.com/*"],>> "%PROJECT_DIR%manifest.json"
echo       "js": ["content.js"],>> "%PROJECT_DIR%manifest.json"
echo       "run_at": "document_start">> "%PROJECT_DIR%manifest.json"
echo     }>> "%PROJECT_DIR%manifest.json"
echo   ],>> "%PROJECT_DIR%manifest.json"
echo   "background": {>> "%PROJECT_DIR%manifest.json"
echo     "service_worker": "background.js">> "%PROJECT_DIR%manifest.json"
echo   },>> "%PROJECT_DIR%manifest.json"
echo   "options_ui": {>> "%PROJECT_DIR%manifest.json"
echo     "page": "options.html",>> "%PROJECT_DIR%manifest.json"
echo     "open_in_tab": false>> "%PROJECT_DIR%manifest.json"
echo   }>> "%PROJECT_DIR%manifest.json"
echo }>> "%PROJECT_DIR%manifest.json"

echo manifest.json dosyasi olusturuldu.

REM content.js dosyasını oluştur
echo content.js dosyasi olusturuluyor...
echo // File: content.js> "%PROJECT_DIR%content.js"
echo // Path: /home/main/public_html/ai.zefre.net/eksi-blocker/content.js>> "%PROJECT_DIR%content.js"
echo // Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%content.js"
echo // Website: https://ai.zefre.net/>> "%PROJECT_DIR%content.js"
echo // R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%content.js"
echo // GitHub: www.github.com/gneral>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Initialize default settings>> "%PROJECT_DIR%content.js"
echo let settings = {>> "%PROJECT_DIR%content.js"
echo   blockBottomStickyAds: true,>> "%PROJECT_DIR%content.js"
echo   blockSidebarAds: true,>> "%PROJECT_DIR%content.js"
echo   blockInlineAds: true,>> "%PROJECT_DIR%content.js"
echo   blockIframes: true>> "%PROJECT_DIR%content.js"
echo };>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Load user settings>> "%PROJECT_DIR%content.js"
echo chrome.storage.sync.get(settings, function(items) {>> "%PROJECT_DIR%content.js"
echo   settings = items;>> "%PROJECT_DIR%content.js"
echo   >> "%PROJECT_DIR%content.js"
echo   // Apply ad blocking immediately>> "%PROJECT_DIR%content.js"
echo   removeAds();>> "%PROJECT_DIR%content.js"
echo   >> "%PROJECT_DIR%content.js"
echo   // Create mutation observer to continually remove ads as they appear>> "%PROJECT_DIR%content.js"
echo   setupAdBlocker();>> "%PROJECT_DIR%content.js"
echo });>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Main function to remove ads based on settings>> "%PROJECT_DIR%content.js"
echo function removeAds() {>> "%PROJECT_DIR%content.js"
echo   // Block iframes (including Google Topics frame)>> "%PROJECT_DIR%content.js"
echo   if (settings.blockIframes) {>> "%PROJECT_DIR%content.js"
echo     const iframes = document.querySelectorAll('iframe');>> "%PROJECT_DIR%content.js"
echo     iframes.forEach(iframe =^> {>> "%PROJECT_DIR%content.js"
echo       if (iframe.src.includes('doubleclick.net') ^|^| >> "%PROJECT_DIR%content.js"
echo           iframe.src.includes('googlesyndication.com') ^|^|>> "%PROJECT_DIR%content.js"
echo           iframe.name === 'goog_topics_frame') {>> "%PROJECT_DIR%content.js"
echo         iframe.remove();>> "%PROJECT_DIR%content.js"
echo       }>> "%PROJECT_DIR%content.js"
echo     });>> "%PROJECT_DIR%content.js"
echo   }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo   // Block sticky bottom ads on mobile>> "%PROJECT_DIR%content.js"
echo   if (settings.blockBottomStickyAds) {>> "%PROJECT_DIR%content.js"
echo     const bottomAds = document.querySelectorAll('ins[id^="gpt_unit_"][style*="bottom: 0px"][style*="position: fixed"]');>> "%PROJECT_DIR%content.js"
echo     bottomAds.forEach(ad =^> ad.remove());>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     // Also remove by container ID>> "%PROJECT_DIR%content.js"
echo     const adContainers = document.querySelectorAll('div[id^="google_ads_iframe_"][id$="__container__"]');>> "%PROJECT_DIR%content.js"
echo     adContainers.forEach(container =^> {>> "%PROJECT_DIR%content.js"
echo       const parent = container.parentElement;>> "%PROJECT_DIR%content.js"
echo       if (parent ^&^& parent.tagName === 'INS') {>> "%PROJECT_DIR%content.js"
echo         parent.remove();>> "%PROJECT_DIR%content.js"
echo       } else {>> "%PROJECT_DIR%content.js"
echo         container.remove();>> "%PROJECT_DIR%content.js"
echo       }>> "%PROJECT_DIR%content.js"
echo     });>> "%PROJECT_DIR%content.js"
echo   }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo   // Block sidebar ads>> "%PROJECT_DIR%content.js"
echo   if (settings.blockSidebarAds) {>> "%PROJECT_DIR%content.js"
echo     // Find elements with class containing "column-container" or "logo-box">> "%PROJECT_DIR%content.js"
echo     const sidebarAds = document.querySelectorAll('div[class*="column-container"], div[class*="logo-box"]');>> "%PROJECT_DIR%content.js"
echo     sidebarAds.forEach(ad =^> {>> "%PROJECT_DIR%content.js"
echo       // Check if it's an ad container by looking for nested elements>> "%PROJECT_DIR%content.js"
echo       if (ad.querySelector('a[href*="googleadservices.com"]') ^|^| >> "%PROJECT_DIR%content.js"
echo           ad.querySelector('div[class*="product-container"]') ^|^|>> "%PROJECT_DIR%content.js"
echo           ad.querySelector('div[class*="logo"]')) {>> "%PROJECT_DIR%content.js"
echo         ad.remove();>> "%PROJECT_DIR%content.js"
echo       }>> "%PROJECT_DIR%content.js"
echo     });>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     // Target specific ad class patterns>> "%PROJECT_DIR%content.js"
echo     document.querySelectorAll('div[class*="cropped-image-intermedia-box"]').forEach(ad =^> ad.remove());>> "%PROJECT_DIR%content.js"
echo   }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo   // Block inline ads (in content)>> "%PROJECT_DIR%content.js"
echo   if (settings.blockInlineAds) {>> "%PROJECT_DIR%content.js"
echo     // Target "hotspot" class ads>> "%PROJECT_DIR%content.js"
echo     document.querySelectorAll('div[class*="hotspot"]').forEach(ad =^> ad.remove());>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     // Target common ad container classes>> "%PROJECT_DIR%content.js"
echo     document.querySelectorAll('div[class*="x-layout"], div[id^="div-gpt-ad"]').forEach(ad =^> ad.remove());>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     // Target class patterns unique to ads>> "%PROJECT_DIR%content.js"
echo     document.querySelectorAll('div[class^="ns-"]').forEach(ad =^> {>> "%PROJECT_DIR%content.js"
echo       // Check if it's an ad container>> "%PROJECT_DIR%content.js"
echo       if (ad.querySelector('a[href*="googleadservices"]') ^|^| >> "%PROJECT_DIR%content.js"
echo           ad.querySelector('div[class*="logo"]') ^|^|>> "%PROJECT_DIR%content.js"
echo           ad.querySelector('div[class*="product"]')) {>> "%PROJECT_DIR%content.js"
echo         ad.remove();>> "%PROJECT_DIR%content.js"
echo       }>> "%PROJECT_DIR%content.js"
echo     });>> "%PROJECT_DIR%content.js"
echo   }>> "%PROJECT_DIR%content.js"
echo }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Set up mutation observer to continuously block ads as they appear>> "%PROJECT_DIR%content.js"
echo function setupAdBlocker() {>> "%PROJECT_DIR%content.js"
echo   const observer = new MutationObserver(mutations =^> {>> "%PROJECT_DIR%content.js"
echo     let shouldRemoveAds = false;>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     for (const mutation of mutations) {>> "%PROJECT_DIR%content.js"
echo       if (mutation.type === 'childList' ^&^& mutation.addedNodes.length ^> 0) {>> "%PROJECT_DIR%content.js"
echo         shouldRemoveAds = true;>> "%PROJECT_DIR%content.js"
echo         break;>> "%PROJECT_DIR%content.js"
echo       }>> "%PROJECT_DIR%content.js"
echo     }>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     if (shouldRemoveAds) {>> "%PROJECT_DIR%content.js"
echo       removeAds();>> "%PROJECT_DIR%content.js"
echo     }>> "%PROJECT_DIR%content.js"
echo   });>> "%PROJECT_DIR%content.js"
echo   >> "%PROJECT_DIR%content.js"
echo   // Start observing the entire document for changes>> "%PROJECT_DIR%content.js"
echo   observer.observe(document.documentElement, {>> "%PROJECT_DIR%content.js"
echo     childList: true,>> "%PROJECT_DIR%content.js"
echo     subtree: true>> "%PROJECT_DIR%content.js"
echo   });>> "%PROJECT_DIR%content.js"
echo }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Apply custom CSS to hide ad spaces>> "%PROJECT_DIR%content.js"
echo function injectStyles() {>> "%PROJECT_DIR%content.js"
echo   const style = document.createElement('style');>> "%PROJECT_DIR%content.js"
echo   style.textContent = `>> "%PROJECT_DIR%content.js"
echo     /* Hide common ad containers */>> "%PROJECT_DIR%content.js"
echo     div[class*="GoogleActiveViewElement"],>> "%PROJECT_DIR%content.js"
echo     div[class*="ad-container"],>> "%PROJECT_DIR%content.js"
echo     div[class*="adbox"],>> "%PROJECT_DIR%content.js"
echo     div[id^="div-gpt-ad"],>> "%PROJECT_DIR%content.js"
echo     ins[id^="gpt_unit_"],>> "%PROJECT_DIR%content.js"
echo     iframe[name="goog_topics_frame"],>> "%PROJECT_DIR%content.js"
echo     div.o43328.el.hotspot,>> "%PROJECT_DIR%content.js"
echo     div[class*="ns-"][data-google-av-adk],>> "%PROJECT_DIR%content.js"
echo     div[class*="logo-box"],>> "%PROJECT_DIR%content.js"
echo     div[class*="product-container"] {>> "%PROJECT_DIR%content.js"
echo       display: none !important;>> "%PROJECT_DIR%content.js"
echo     }>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     /* Fix layout after removing ads */>> "%PROJECT_DIR%content.js"
echo     body {>> "%PROJECT_DIR%content.js"
echo       overflow: auto !important;>> "%PROJECT_DIR%content.js"
echo     }>> "%PROJECT_DIR%content.js"
echo     >> "%PROJECT_DIR%content.js"
echo     /* Ensure no space is reserved for removed ads */>> "%PROJECT_DIR%content.js"
echo     div[style*="bottom: 0px"][style*="position: fixed"] {>> "%PROJECT_DIR%content.js"
echo       display: none !important;>> "%PROJECT_DIR%content.js"
echo     }>> "%PROJECT_DIR%content.js"
echo   `;>> "%PROJECT_DIR%content.js"
echo   document.head.appendChild(style);>> "%PROJECT_DIR%content.js"
echo }>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Inject CSS as early as possible>> "%PROJECT_DIR%content.js"
echo injectStyles();>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Run again when DOM is fully loaded>> "%PROJECT_DIR%content.js"
echo document.addEventListener('DOMContentLoaded', function() {>> "%PROJECT_DIR%content.js"
echo   removeAds();>> "%PROJECT_DIR%content.js"
echo   injectStyles();>> "%PROJECT_DIR%content.js"
echo });>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Also run when page is fully loaded with resources>> "%PROJECT_DIR%content.js"
echo window.addEventListener('load', function() {>> "%PROJECT_DIR%content.js"
echo   removeAds();>> "%PROJECT_DIR%content.js"
echo });>> "%PROJECT_DIR%content.js"
echo.>> "%PROJECT_DIR%content.js"
echo // Run periodically to catch any delayed ads>> "%PROJECT_DIR%content.js"
echo setInterval(removeAds, 2000);>> "%PROJECT_DIR%content.js"

echo content.js dosyasi olusturuldu.

REM background.js dosyasını oluştur
echo background.js dosyasi olusturuluyor...
echo // File: background.js> "%PROJECT_DIR%background.js"
echo // Path: /home/main/public_html/ai.zefre.net/eksi-blocker/background.js>> "%PROJECT_DIR%background.js"
echo // Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%background.js"
echo // Website: https://ai.zefre.net/>> "%PROJECT_DIR%background.js"
echo // R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%background.js"
echo // GitHub: www.github.com/gneral>> "%PROJECT_DIR%background.js"
echo.>> "%PROJECT_DIR%background.js"
echo // Initialize default settings if not already set>> "%PROJECT_DIR%background.js"
echo chrome.runtime.onInstalled.addListener(function() {>> "%PROJECT_DIR%background.js"
echo   chrome.storage.sync.get({>> "%PROJECT_DIR%background.js"
echo     blockBottomStickyAds: true,>> "%PROJECT_DIR%background.js"
echo     blockSidebarAds: true,>> "%PROJECT_DIR%background.js"
echo     blockInlineAds: true,>> "%PROJECT_DIR%background.js"
echo     blockIframes: true,>> "%PROJECT_DIR%background.js"
echo     enabled: true>> "%PROJECT_DIR%background.js"
echo   }, function(items) {>> "%PROJECT_DIR%background.js"
echo     // Save default settings if they don't exist>> "%PROJECT_DIR%background.js"
echo     chrome.storage.sync.set(items);>> "%PROJECT_DIR%background.js"
echo   });>> "%PROJECT_DIR%background.js"
echo });>> "%PROJECT_DIR%background.js"
echo.>> "%PROJECT_DIR%background.js"
echo // Listen for messages from popup or options page>> "%PROJECT_DIR%background.js"
echo chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {>> "%PROJECT_DIR%background.js"
echo   if (request.action === "getStatus") {>> "%PROJECT_DIR%background.js"
echo     chrome.storage.sync.get({>> "%PROJECT_DIR%background.js"
echo       enabled: true>> "%PROJECT_DIR%background.js"
echo     }, function(items) {>> "%PROJECT_DIR%background.js"
echo       sendResponse({enabled: items.enabled});>> "%PROJECT_DIR%background.js"
echo     });>> "%PROJECT_DIR%background.js"
echo     return true; // Important: indicates async response>> "%PROJECT_DIR%background.js"
echo   }>> "%PROJECT_DIR%background.js"
echo   >> "%PROJECT_DIR%background.js"
echo   if (request.action === "toggleEnabled") {>> "%PROJECT_DIR%background.js"
echo     chrome.storage.sync.set({>> "%PROJECT_DIR%background.js"
echo       enabled: request.enabled>> "%PROJECT_DIR%background.js"
echo     }, function() {>> "%PROJECT_DIR%background.js"
echo       // Reload active eksisozluk tabs>> "%PROJECT_DIR%background.js"
echo       chrome.tabs.query({>> "%PROJECT_DIR%background.js"
echo         url: ["*://eksisozluk.com/*", "*://*.eksisozluk.com/*"]>> "%PROJECT_DIR%background.js"
echo       }, function(tabs) {>> "%PROJECT_DIR%background.js"
echo         tabs.forEach(function(tab) {>> "%PROJECT_DIR%background.js"
echo           chrome.tabs.reload(tab.id);>> "%PROJECT_DIR%background.js"
echo         });>> "%PROJECT_DIR%background.js"
echo       });>> "%PROJECT_DIR%background.js"
echo       >> "%PROJECT_DIR%background.js"
echo       sendResponse({status: "success"});>> "%PROJECT_DIR%background.js"
echo     });>> "%PROJECT_DIR%background.js"
echo     return true; // Important: indicates async response>> "%PROJECT_DIR%background.js"
echo   }>> "%PROJECT_DIR%background.js"
echo   >> "%PROJECT_DIR%background.js"
echo   if (request.action === "updateSettings") {>> "%PROJECT_DIR%background.js"
echo     chrome.storage.sync.set(request.settings, function() {>> "%PROJECT_DIR%background.js"
echo       // Reload active eksisozluk tabs>> "%PROJECT_DIR%background.js"
echo       chrome.tabs.query({>> "%PROJECT_DIR%background.js"
echo         url: ["*://eksisozluk.com/*", "*://*.eksisozluk.com/*"]>> "%PROJECT_DIR%background.js"
echo       }, function(tabs) {>> "%PROJECT_DIR%background.js"
echo         tabs.forEach(function(tab) {>> "%PROJECT_DIR%background.js"
echo           chrome.tabs.reload(tab.id);>> "%PROJECT_DIR%background.js"
echo         });>> "%PROJECT_DIR%background.js"
echo       });>> "%PROJECT_DIR%background.js"
echo       >> "%PROJECT_DIR%background.js"
echo       sendResponse({status: "success"});>> "%PROJECT_DIR%background.js"
echo     });>> "%PROJECT_DIR%background.js"
echo     return true; // Important: indicates async response>> "%PROJECT_DIR%background.js"
echo   }>> "%PROJECT_DIR%background.js"
echo });>> "%PROJECT_DIR%background.js"

echo background.js dosyasi olusturuldu.

REM popup.html dosyasını oluştur
echo popup.html dosyasi olusturuluyor...
echo ^<!DOCTYPE html^>> "%PROJECT_DIR%popup.html"
echo ^<!-- >> "%PROJECT_DIR%popup.html"
echo   File: popup.html>> "%PROJECT_DIR%popup.html"
echo   Path: /home/main/public_html/ai.zefre.net/eksi-blocker/popup.html>> "%PROJECT_DIR%popup.html"
echo   Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%popup.html"
echo   Website: https://ai.zefre.net/>> "%PROJECT_DIR%popup.html"
echo   R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%popup.html"
echo   GitHub: www.github.com/gneral>> "%PROJECT_DIR%popup.html"
echo --^>> "%PROJECT_DIR%popup.html"
echo ^<html lang="tr"^>> "%PROJECT_DIR%popup.html"
echo ^<head^>> "%PROJECT_DIR%popup.html"
echo   ^<meta charset="UTF-8"^>> "%PROJECT_DIR%popup.html"
echo   ^<meta name="viewport" content="width=device-width, initial-scale=1.0"^>> "%PROJECT_DIR%popup.html"
echo   ^<title^>Ekşi Sözlük Ad Blocker^</title^>> "%PROJECT_DIR%popup.html"
echo   ^<style^>> "%PROJECT_DIR%popup.html"
echo     body {>> "%PROJECT_DIR%popup.html"
echo       font-family: Arial, sans-serif;>> "%PROJECT_DIR%popup.html"
echo       width: 250px;>> "%PROJECT_DIR%popup.html"
echo       padding: 15px;>> "%PROJECT_DIR%popup.html"
echo       margin: 0;>> "%PROJECT_DIR%popup.html"
echo       color: #333;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     h1 {>> "%PROJECT_DIR%popup.html"
echo       font-size: 16px;>> "%PROJECT_DIR%popup.html"
echo       margin-top: 0;>> "%PROJECT_DIR%popup.html"
echo       margin-bottom: 15px;>> "%PROJECT_DIR%popup.html"
echo       text-align: center;>> "%PROJECT_DIR%popup.html"
echo       color: #81C14B;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .toggle-container {>> "%PROJECT_DIR%popup.html"
echo       display: flex;>> "%PROJECT_DIR%popup.html"
echo       align-items: center;>> "%PROJECT_DIR%popup.html"
echo       justify-content: space-between;>> "%PROJECT_DIR%popup.html"
echo       margin-bottom: 15px;>> "%PROJECT_DIR%popup.html"
echo       padding-bottom: 15px;>> "%PROJECT_DIR%popup.html"
echo       border-bottom: 1px solid #eee;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .toggle-switch {>> "%PROJECT_DIR%popup.html"
echo       position: relative;>> "%PROJECT_DIR%popup.html"
echo       display: inline-block;>> "%PROJECT_DIR%popup.html"
echo       width: 50px;>> "%PROJECT_DIR%popup.html"
echo       height: 24px;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .toggle-switch input {>> "%PROJECT_DIR%popup.html"
echo       opacity: 0;>> "%PROJECT_DIR%popup.html"
echo       width: 0;>> "%PROJECT_DIR%popup.html"
echo       height: 0;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .slider {>> "%PROJECT_DIR%popup.html"
echo       position: absolute;>> "%PROJECT_DIR%popup.html"
echo       cursor: pointer;>> "%PROJECT_DIR%popup.html"
echo       top: 0;>> "%PROJECT_DIR%popup.html"
echo       left: 0;>> "%PROJECT_DIR%popup.html"
echo       right: 0;>> "%PROJECT_DIR%popup.html"
echo       bottom: 0;>> "%PROJECT_DIR%popup.html"
echo       background-color: #ccc;>> "%PROJECT_DIR%popup.html"
echo       transition: .4s;>> "%PROJECT_DIR%popup.html"
echo       border-radius: 24px;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .slider:before {>> "%PROJECT_DIR%popup.html"
echo       position: absolute;>> "%PROJECT_DIR%popup.html"
echo       content: "";>> "%PROJECT_DIR%popup.html"
echo       height: 16px;>> "%PROJECT_DIR%popup.html"
echo       width: 16px;>> "%PROJECT_DIR%popup.html"
echo       left: 4px;>> "%PROJECT_DIR%popup.html"
echo       bottom: 4px;>> "%PROJECT_DIR%popup.html"
echo       background-color: white;>> "%PROJECT_DIR%popup.html"
echo       transition: .4s;>> "%PROJECT_DIR%popup.html"
echo       border-radius: 50%%;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     input:checked + .slider {>> "%PROJECT_DIR%popup.html"
echo       background-color: #81C14B;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     input:checked + .slider:before {>> "%PROJECT_DIR%popup.html"
echo       transform: translateX(26px);>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .status {>> "%PROJECT_DIR%popup.html"
echo       font-weight: bold;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .button {>> "%PROJECT_DIR%popup.html"
echo       display: block;>> "%PROJECT_DIR%popup.html"
echo       width: 100%%;>> "%PROJECT_DIR%popup.html"
echo       padding: 10px 0;>> "%PROJECT_DIR%popup.html"
echo       margin-top: 10px;>> "%PROJECT_DIR%popup.html"
echo       background-color: #81C14B;>> "%PROJECT_DIR%popup.html"
echo       color: white;>> "%PROJECT_DIR%popup.html"
echo       border: none;>> "%PROJECT_DIR%popup.html"
echo       border-radius: 4px;>> "%PROJECT_DIR%popup.html"
echo       cursor: pointer;>> "%PROJECT_DIR%popup.html"
echo       text-align: center;>> "%PROJECT_DIR%popup.html"
echo       text-decoration: none;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .button:hover {>> "%PROJECT_DIR%popup.html"
echo       background-color: #6BA53E;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo     >> "%PROJECT_DIR%popup.html"
echo     .footer {>> "%PROJECT_DIR%popup.html"
echo       margin-top: 20px;>> "%PROJECT_DIR%popup.html"
echo       font-size: 11px;>> "%PROJECT_DIR%popup.html"
echo       color: #999;>> "%PROJECT_DIR%popup.html"
echo       text-align: center;>> "%PROJECT_DIR%popup.html"
echo     }>> "%PROJECT_DIR%popup.html"
echo   ^</style^>> "%PROJECT_DIR%popup.html"
echo ^</head^>> "%PROJECT_DIR%popup.html"
echo ^<body^>> "%PROJECT_DIR%popup.html"
echo   ^<h1^>Ekşi Sözlük Ad Blocker^</h1^>> "%PROJECT_DIR%popup.html"
echo   >> "%PROJECT_DIR%popup.html"
echo   ^<div class="toggle-container"^>> "%PROJECT_DIR%popup.html"
echo     ^<span^>Etkinleştir:^</span^>> "%PROJECT_DIR%popup.html"
echo     ^<label class="toggle-switch"^>> "%PROJECT_DIR%popup.html"
echo       ^<input type="checkbox" id="enabledToggle"^>> "%PROJECT_DIR%popup.html"
echo       ^<span class="slider"^>^</span^>> "%PROJECT_DIR%popup.html"
echo     ^</label^>> "%PROJECT_DIR%popup.html"
echo   ^</div^>> "%PROJECT_DIR%popup.html"
echo   >> "%PROJECT_DIR%popup.html"
echo   ^<div id="statusText" class="status"^>Durum: Yükleniyor...^</div^>> "%PROJECT_DIR%popup.html"
echo   >> "%PROJECT_DIR%popup.html"
echo   ^<a href="#" id="optionsBtn" class="button"^>Ayarlar^</a^>> "%PROJECT_DIR%popup.html"
echo   >> "%PROJECT_DIR%popup.html"
echo   ^<div class="footer"^>> "%PROJECT_DIR%popup.html"
echo     Geliştirici: gneral ^&copy; 2025>> "%PROJECT_DIR%popup.html"
echo   ^</div^>> "%PROJECT_DIR%popup.html"
echo   >> "%PROJECT_DIR%popup.html"
echo   ^<script src="popup.js"^>^</script^>> "%PROJECT_DIR%popup.html"
echo ^</body^>> "%PROJECT_DIR%popup.html"
echo ^</html^>> "%PROJECT_DIR%popup.html"

echo popup.html dosyasi olusturuldu.

REM popup.js dosyasını oluştur
echo popup.js dosyasi olusturuluyor...
echo // File: popup.js> "%PROJECT_DIR%popup.js"
echo // Path: /home/main/public_html/ai.zefre.net/eksi-blocker/popup.js>> "%PROJECT_DIR%popup.js"
echo // Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%popup.js"
echo // Website: https://ai.zefre.net/>> "%PROJECT_DIR%popup.js"
echo // R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%popup.js"
echo // GitHub: www.github.com/gneral>> "%PROJECT_DIR%popup.js"
echo.>> "%PROJECT_DIR%popup.js"
echo document.addEventListener('DOMContentLoaded', function() {>> "%PROJECT_DIR%popup.js"
echo   const enabledToggle = document.getElementById('enabledToggle');>> "%PROJECT_DIR%popup.js"
echo   const statusText = document.getElementById('statusText');>> "%PROJECT_DIR%popup.js"
echo   const optionsBtn = document.getElementById('optionsBtn');>> "%PROJECT_DIR%popup.js"
echo   >> "%PROJECT_DIR%popup.js"
echo   // Load current state>> "%PROJECT_DIR%popup.js"
echo   chrome.runtime.sendMessage({action: "getStatus"}, function(response) {>> "%PROJECT_DIR%popup.js"
echo     if (response ^&^& response.hasOwnProperty('enabled')) {>> "%PROJECT_DIR%popup.js"
echo       enabledToggle.checked = response.enabled;>> "%PROJECT_DIR%popup.js"
echo       updateStatusText(response.enabled);>> "%PROJECT_DIR%popup.js"
echo     }>> "%PROJECT_DIR%popup.js"
echo   });>> "%PROJECT_DIR%popup.js"
echo   >> "%PROJECT_DIR%popup.js"
echo   // Toggle extension enabled state>> "%PROJECT_DIR%popup.js"
echo   enabledToggle.addEventListener('change', function() {>> "%PROJECT_DIR%popup.js"
echo     chrome.runtime.sendMessage({>> "%PROJECT_DIR%popup.js"
echo       action: "toggleEnabled",>> "%PROJECT_DIR%popup.js"
echo       enabled: enabledToggle.checked>> "%PROJECT_DIR%popup.js"
echo     }, function(response) {>> "%PROJECT_DIR%popup.js"
echo       if (response ^&^& response.status === "success") {>> "%PROJECT_DIR%popup.js"
echo         updateStatusText(enabledToggle.checked);>> "%PROJECT_DIR%popup.js"
echo       }>> "%PROJECT_DIR%popup.js"
echo     });>> "%PROJECT_DIR%popup.js"
echo   });>> "%PROJECT_DIR%popup.js"
echo   >> "%PROJECT_DIR%popup.js"
echo   // Open options page>> "%PROJECT_DIR%popup.js"
echo   optionsBtn.addEventListener('click', function(e) {>> "%PROJECT_DIR%popup.js"
echo     e.preventDefault();>> "%PROJECT_DIR%popup.js"
echo     chrome.runtime.openOptionsPage();>> "%PROJECT_DIR%popup.js"
echo   });>> "%PROJECT_DIR%popup.js"
echo   >> "%PROJECT_DIR%popup.js"
echo   // Update status text based on enabled state>> "%PROJECT_DIR%popup.js"
echo   function updateStatusText(enabled) {>> "%PROJECT_DIR%popup.js"
echo     if (enabled) {>> "%PROJECT_DIR%popup.js"
echo       statusText.textContent = 'Durum: Aktif';>> "%PROJECT_DIR%popup.js"
echo       statusText.style.color = '#81C14B';>> "%PROJECT_DIR%popup.js"
echo     } else {>> "%PROJECT_DIR%popup.js"
echo       statusText.textContent = 'Durum: Devre Dışı';>> "%PROJECT_DIR%popup.js"
echo       statusText.style.color = '#999';>> "%PROJECT_DIR%popup.js"
echo     }>> "%PROJECT_DIR%popup.js"
echo   }>> "%PROJECT_DIR%popup.js"
echo });>> "%PROJECT_DIR%popup.js"

echo popup.js dosyasi olusturuldu.

REM options.html dosyasını oluştur
echo options.html dosyasi olusturuluyor...
echo ^<!DOCTYPE html^>> "%PROJECT_DIR%options.html"
echo ^<!-- >> "%PROJECT_DIR%options.html"
echo   File: options.html>> "%PROJECT_DIR%options.html"
echo   Path: /home/main/public_html/ai.zefre.net/eksi-blocker/options.html>> "%PROJECT_DIR%options.html"
echo   Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%options.html"
echo   Website: https://ai.zefre.net/>> "%PROJECT_DIR%options.html"
echo   R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%options.html"
echo   GitHub: www.github.com/gneral>> "%PROJECT_DIR%options.html"
echo --^>> "%PROJECT_DIR%options.html"
echo ^<html lang="tr"^>> "%PROJECT_DIR%options.html"
echo ^<head^>> "%PROJECT_DIR%options.html"
echo   ^<meta charset="UTF-8"^>> "%PROJECT_DIR%options.html"
echo   ^<meta name="viewport" content="width=device-width, initial-scale=1.0"^>> "%PROJECT_DIR%options.html"
echo   ^<title^>Ekşi Sözlük Ad Blocker - Ayarlar^</title^>> "%PROJECT_DIR%options.html"
echo   ^<style^>> "%PROJECT_DIR%options.html"
echo     body {>> "%PROJECT_DIR%options.html"
echo       font-family: Arial, sans-serif;>> "%PROJECT_DIR%options.html"
echo       width: 100%%;>> "%PROJECT_DIR%options.html"
echo       max-width: 500px;>> "%PROJECT_DIR%options.html"
echo       margin: 0 auto;>> "%PROJECT_DIR%options.html"
echo       padding: 20px;>> "%PROJECT_DIR%options.html"
echo       color: #333;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     h1 {>> "%PROJECT_DIR%options.html"
echo       font-size: 20px;>> "%PROJECT_DIR%options.html"
echo       margin-top: 0;>> "%PROJECT_DIR%options.html"
echo       margin-bottom: 20px;>> "%PROJECT_DIR%options.html"
echo       color: #81C14B;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .option-container {>> "%PROJECT_DIR%options.html"
echo       margin-bottom: 15px;>> "%PROJECT_DIR%options.html"
echo       padding-bottom: 15px;>> "%PROJECT_DIR%options.html"
echo       border-bottom: 1px solid #eee;>> "%PROJECT_DIR%options.html"
echo       display: flex;>> "%PROJECT_DIR%options.html"
echo       justify-content: space-between;>> "%PROJECT_DIR%options.html"
echo       align-items: center;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .option-info {>> "%PROJECT_DIR%options.html"
echo       flex-grow: 1;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .option-title {>> "%PROJECT_DIR%options.html"
echo       font-weight: bold;>> "%PROJECT_DIR%options.html"
echo       margin-bottom: 5px;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .option-description {>> "%PROJECT_DIR%options.html"
echo       font-size: 12px;>> "%PROJECT_DIR%options.html"
echo       color: #666;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .toggle-switch {>> "%PROJECT_DIR%options.html"
echo       position: relative;>> "%PROJECT_DIR%options.html"
echo       display: inline-block;>> "%PROJECT_DIR%options.html"
echo       width: 50px;>> "%PROJECT_DIR%options.html"
echo       height: 24px;>> "%PROJECT_DIR%options.html"
echo       margin-left: 20px;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .toggle-switch input {>> "%PROJECT_DIR%options.html"
echo       opacity: 0;>> "%PROJECT_DIR%options.html"
echo       width: 0;>> "%PROJECT_DIR%options.html"
echo       height: 0;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .slider {>> "%PROJECT_DIR%options.html"
echo       position: absolute;>> "%PROJECT_DIR%options.html"
echo       cursor: pointer;>> "%PROJECT_DIR%options.html"
echo       top: 0;>> "%PROJECT_DIR%options.html"
echo       left: 0;>> "%PROJECT_DIR%options.html"
echo       right: 0;>> "%PROJECT_DIR%options.html"
echo       bottom: 0;>> "%PROJECT_DIR%options.html"
echo       background-color: #ccc;>> "%PROJECT_DIR%options.html"
echo       transition: .4s;>> "%PROJECT_DIR%options.html"
echo       border-radius: 24px;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .slider:before {>> "%PROJECT_DIR%options.html"
echo       position: absolute;>> "%PROJECT_DIR%options.html"
echo       content: "";>> "%PROJECT_DIR%options.html"
echo       height: 16px;>> "%PROJECT_DIR%options.html"
echo       width: 16px;>> "%PROJECT_DIR%options.html"
echo       left: 4px;>> "%PROJECT_DIR%options.html"
echo       bottom: 4px;>> "%PROJECT_DIR%options.html"
echo       background-color: white;>> "%PROJECT_DIR%options.html"
echo       transition: .4s;>> "%PROJECT_DIR%options.html"
echo       border-radius: 50%%;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     input:checked + .slider {>> "%PROJECT_DIR%options.html"
echo       background-color: #81C14B;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     input:checked + .slider:before {>> "%PROJECT_DIR%options.html"
echo       transform: translateX(26px);>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .actions {>> "%PROJECT_DIR%options.html"
echo       margin-top: 20px;>> "%PROJECT_DIR%options.html"
echo       text-align: right;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .button {>> "%PROJECT_DIR%options.html"
echo       padding: 8px 16px;>> "%PROJECT_DIR%options.html"
echo       background-color: #81C14B;>> "%PROJECT_DIR%options.html"
echo       color: white;>> "%PROJECT_DIR%options.html"
echo       border: none;>> "%PROJECT_DIR%options.html"
echo       border-radius: 4px;>> "%PROJECT_DIR%options.html"
echo       cursor: pointer;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .button:hover {>> "%PROJECT_DIR%options.html"
echo       background-color: #6BA53E;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .button.secondary {>> "%PROJECT_DIR%options.html"
echo       background-color: #ccc;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .button.secondary:hover {>> "%PROJECT_DIR%options.html"
echo       background-color: #bbb;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .footer {>> "%PROJECT_DIR%options.html"
echo       margin-top: 30px;>> "%PROJECT_DIR%options.html"
echo       font-size: 12px;>> "%PROJECT_DIR%options.html"
echo       color: #999;>> "%PROJECT_DIR%options.html"
echo       text-align: center;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .status-message {>> "%PROJECT_DIR%options.html"
echo       margin-top: 15px;>> "%PROJECT_DIR%options.html"
echo       padding: 8px;>> "%PROJECT_DIR%options.html"
echo       border-radius: 4px;>> "%PROJECT_DIR%options.html"
echo       text-align: center;>> "%PROJECT_DIR%options.html"
echo       display: none;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .status-message.success {>> "%PROJECT_DIR%options.html"
echo       background-color: #e8f5e9;>> "%PROJECT_DIR%options.html"
echo       color: #2e7d32;>> "%PROJECT_DIR%options.html"
echo       display: block;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo     >> "%PROJECT_DIR%options.html"
echo     .status-message.error {>> "%PROJECT_DIR%options.html"
echo       background-color: #ffebee;>> "%PROJECT_DIR%options.html"
echo       color: #c62828;>> "%PROJECT_DIR%options.html"
echo       display: block;>> "%PROJECT_DIR%options.html"
echo     }>> "%PROJECT_DIR%options.html"
echo   ^</style^>> "%PROJECT_DIR%options.html"
echo ^</head^>> "%PROJECT_DIR%options.html"
echo ^<body^>> "%PROJECT_DIR%options.html"
echo   ^<h1^>Ekşi Sözlük Ad Blocker - Ayarlar^</h1^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div id="statusMessage" class="status-message"^>^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="option-container"^>> "%PROJECT_DIR%options.html"
echo     ^<div class="option-info"^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-title"^>Alt Sabit Reklamları Engelle^</div^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-description"^>Mobil görünümde sayfanın altında yer alan sabit reklamları engeller.^</div^>> "%PROJECT_DIR%options.html"
echo     ^</div^>> "%PROJECT_DIR%options.html"
echo     ^<label class="toggle-switch"^>> "%PROJECT_DIR%options.html"
echo       ^<input type="checkbox" id="blockBottomStickyAds"^>> "%PROJECT_DIR%options.html"
echo       ^<span class="slider"^>^</span^>> "%PROJECT_DIR%options.html"
echo     ^</label^>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="option-container"^>> "%PROJECT_DIR%options.html"
echo     ^<div class="option-info"^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-title"^>Kenar Çubuğu Reklamlarını Engelle^</div^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-description"^>Sayfa kenarlarında yer alan reklam kutularını engeller.^</div^>> "%PROJECT_DIR%options.html"
echo     ^</div^>> "%PROJECT_DIR%options.html"
echo     ^<label class="toggle-switch"^>> "%PROJECT_DIR%options.html"
echo       ^<input type="checkbox" id="blockSidebarAds"^>> "%PROJECT_DIR%options.html"
echo       ^<span class="slider"^>^</span^>> "%PROJECT_DIR%options.html"
echo     ^</label^>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="option-container"^>> "%PROJECT_DIR%options.html"
echo     ^<div class="option-info"^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-title"^>İçerik İçi Reklamları Engelle^</div^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-description"^>Entry'lerin arasında yer alan reklamları engeller.^</div^>> "%PROJECT_DIR%options.html"
echo     ^</div^>> "%PROJECT_DIR%options.html"
echo     ^<label class="toggle-switch"^>> "%PROJECT_DIR%options.html"
echo       ^<input type="checkbox" id="blockInlineAds"^>> "%PROJECT_DIR%options.html"
echo       ^<span class="slider"^>^</span^>> "%PROJECT_DIR%options.html"
echo     ^</label^>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="option-container"^>> "%PROJECT_DIR%options.html"
echo     ^<div class="option-info"^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-title"^>IFrame Reklamları Engelle^</div^>> "%PROJECT_DIR%options.html"
echo       ^<div class="option-description"^>Google Topics ve diğer iframe reklamlarını engeller.^</div^>> "%PROJECT_DIR%options.html"
echo     ^</div^>> "%PROJECT_DIR%options.html"
echo     ^<label class="toggle-switch"^>> "%PROJECT_DIR%options.html"
echo       ^<input type="checkbox" id="blockIframes"^>> "%PROJECT_DIR%options.html"
echo       ^<span class="slider"^>^</span^>> "%PROJECT_DIR%options.html"
echo     ^</label^>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="actions"^>> "%PROJECT_DIR%options.html"
echo     ^<button id="resetButton" class="button secondary"^>Varsayılana Sıfırla^</button^>> "%PROJECT_DIR%options.html"
echo     ^<button id="saveButton" class="button"^>Kaydet^</button^>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<div class="footer"^>> "%PROJECT_DIR%options.html"
echo     Ekşi Sözlük Ad Blocker v1.0.0^<br^>>> "%PROJECT_DIR%options.html"
echo     Geliştirici: gneral ^&copy; 2025>> "%PROJECT_DIR%options.html"
echo   ^</div^>> "%PROJECT_DIR%options.html"
echo   >> "%PROJECT_DIR%options.html"
echo   ^<script src="options.js"^>^</script^>> "%PROJECT_DIR%options.html"
echo ^</body^>> "%PROJECT_DIR%options.html"
echo ^</html^>> "%PROJECT_DIR%options.html"

echo options.html dosyasi olusturuldu.

REM options.js dosyasını oluştur
echo options.js dosyasi olusturuluyor...
echo // File: options.js> "%PROJECT_DIR%options.js"
echo // Path: /home/main/public_html/ai.zefre.net/eksi-blocker/options.js>> "%PROJECT_DIR%options.js"
echo // Developer: gneral ^<gneral@gmail.com^>>> "%PROJECT_DIR%options.js"
echo // Website: https://ai.zefre.net/>> "%PROJECT_DIR%options.js"
echo // R10 Profile: https://www.r10.net/profil/193-gneral.html>> "%PROJECT_DIR%options.js"
echo // GitHub: www.github.com/gneral>> "%PROJECT_DIR%options.js"
echo.>> "%PROJECT_DIR%options.js"
echo document.addEventListener('DOMContentLoaded', function() {>> "%PROJECT_DIR%options.js"
echo   // Get elements>> "%PROJECT_DIR%options.js"
echo   const blockBottomStickyAds = document.getElementById('blockBottomStickyAds');>> "%PROJECT_DIR%options.js"
echo   const blockSidebarAds = document.getElementById('blockSidebarAds');>> "%PROJECT_DIR%options.js"
echo   const blockInlineAds = document.getElementById('blockInlineAds');>> "%PROJECT_DIR%options.js"
echo   const blockIframes = document.getElementById('blockIframes');>> "%PROJECT_DIR%options.js"
echo   const saveButton = document.getElementById('saveButton');>> "%PROJECT_DIR%options.js"
echo   const resetButton = document.getElementById('resetButton');>> "%PROJECT_DIR%options.js"
echo   const statusMessage = document.getElementById('statusMessage');>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Load current settings>> "%PROJECT_DIR%options.js"
echo   loadSettings();>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Save settings when Save button is clicked>> "%PROJECT_DIR%options.js"
echo   saveButton.addEventListener('click', function() {>> "%PROJECT_DIR%options.js"
echo     saveSettings();>> "%PROJECT_DIR%options.js"
echo   });>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Reset to defaults when Reset button is clicked>> "%PROJECT_DIR%options.js"
echo   resetButton.addEventListener('click', function() {>> "%PROJECT_DIR%options.js"
echo     resetSettings();>> "%PROJECT_DIR%options.js"
echo   });>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Load settings from storage>> "%PROJECT_DIR%options.js"
echo   function loadSettings() {>> "%PROJECT_DIR%options.js"
echo     chrome.storage.sync.get({>> "%PROJECT_DIR%options.js"
echo       blockBottomStickyAds: true,>> "%PROJECT_DIR%options.js"
echo       blockSidebarAds: true,>> "%PROJECT_DIR%options.js"
echo       blockInlineAds: true,>> "%PROJECT_DIR%options.js"
echo       blockIframes: true>> "%PROJECT_DIR%options.js"
echo     }, function(items) {>> "%PROJECT_DIR%options.js"
echo       blockBottomStickyAds.checked = items.blockBottomStickyAds;>> "%PROJECT_DIR%options.js"
echo       blockSidebarAds.checked = items.blockSidebarAds;>> "%PROJECT_DIR%options.js"
echo       blockInlineAds.checked = items.blockInlineAds;>> "%PROJECT_DIR%options.js"
echo       blockIframes.checked = items.blockIframes;>> "%PROJECT_DIR%options.js"
echo     });>> "%PROJECT_DIR%options.js"
echo   }>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Save settings to storage>> "%PROJECT_DIR%options.js"
echo   function saveSettings() {>> "%PROJECT_DIR%options.js"
echo     const settings = {>> "%PROJECT_DIR%options.js"
echo       blockBottomStickyAds: blockBottomStickyAds.checked,>> "%PROJECT_DIR%options.js"
echo       blockSidebarAds: blockSidebarAds.checked,>> "%PROJECT_DIR%options.js"
echo       blockInlineAds: blockInlineAds.checked,>> "%PROJECT_DIR%options.js"
echo       blockIframes: blockIframes.checked>> "%PROJECT_DIR%options.js"
echo     };>> "%PROJECT_DIR%options.js"
echo     >> "%PROJECT_DIR%options.js"
echo     chrome.runtime.sendMessage({>> "%PROJECT_DIR%options.js"
echo       action: "updateSettings",>> "%PROJECT_DIR%options.js"
echo       settings: settings>> "%PROJECT_DIR%options.js"
echo     }, function(response) {>> "%PROJECT_DIR%options.js"
echo       if (response ^&^& response.status === "success") {>> "%PROJECT_DIR%options.js"
echo         showStatusMessage("Ayarlar başarıyla kaydedildi.", "success");>> "%PROJECT_DIR%options.js"
echo       } else {>> "%PROJECT_DIR%options.js"
echo         showStatusMessage("Ayarlar kaydedilirken bir hata oluştu.", "error");>> "%PROJECT_DIR%options.js"
echo       }>> "%PROJECT_DIR%options.js"
echo     });>> "%PROJECT_DIR%options.js"
echo   }>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Reset settings to defaults>> "%PROJECT_DIR%options.js"
echo   function resetSettings() {>> "%PROJECT_DIR%options.js"
echo     const defaultSettings = {>> "%PROJECT_DIR%options.js"
echo       blockBottomStickyAds: true,>> "%PROJECT_DIR%options.js"
echo       blockSidebarAds: true,>> "%PROJECT_DIR%options.js"
echo       blockInlineAds: true,>> "%PROJECT_DIR%options.js"
echo       blockIframes: true>> "%PROJECT_DIR%options.js"
echo     };>> "%PROJECT_DIR%options.js"
echo     >> "%PROJECT_DIR%options.js"
echo     blockBottomStickyAds.checked = defaultSettings.blockBottomStickyAds;>> "%PROJECT_DIR%options.js"
echo     blockSidebarAds.checked = defaultSettings.blockSidebarAds;>> "%PROJECT_DIR%options.js"
echo     blockInlineAds.checked = defaultSettings.blockInlineAds;>> "%PROJECT_DIR%options.js"
echo     blockIframes.checked = defaultSettings.blockIframes;>> "%PROJECT_DIR%options.js"
echo     >> "%PROJECT_DIR%options.js"
echo     chrome.runtime.sendMessage({>> "%PROJECT_DIR%options.js"
echo       action: "updateSettings",>> "%PROJECT_DIR%options.js"
echo       settings: defaultSettings>> "%PROJECT_DIR%options.js"
echo     }, function(response) {>> "%PROJECT_DIR%options.js"
echo       if (response ^&^& response.status === "success") {>> "%PROJECT_DIR%options.js"
echo         showStatusMessage("Ayarlar varsayılana sıfırlandı.", "success");>> "%PROJECT_DIR%options.js"
echo       } else {>> "%PROJECT_DIR%options.js"
echo         showStatusMessage("Ayarlar sıfırlanırken bir hata oluştu.", "error");>> "%PROJECT_DIR%options.js"
echo       }>> "%PROJECT_DIR%options.js"
echo     });>> "%PROJECT_DIR%options.js"
echo   }>> "%PROJECT_DIR%options.js"
echo   >> "%PROJECT_DIR%options.js"
echo   // Show status message>> "%PROJECT_DIR%options.js"
echo   function showStatusMessage(message, type) {>> "%PROJECT_DIR%options.js"
echo     statusMessage.textContent = message;>> "%PROJECT_DIR%options.js"
echo     statusMessage.className = 'status-message ' + type;>> "%PROJECT_DIR%options.js"
echo     >> "%PROJECT_DIR%options.js"
echo     // Auto-hide after 3 seconds>> "%PROJECT_DIR%options.js"
echo     setTimeout(function() {>> "%PROJECT_DIR%options.js"
echo       statusMessage.className = 'status-message';>> "%PROJECT_DIR%options.js"
echo     }, 3000);>> "%PROJECT_DIR%options.js"
echo   }>> "%PROJECT_DIR%options.js"
echo });>> "%PROJECT_DIR%options.js"

echo options.js dosyasi olusturuldu.

REM Eğer setup.sh varsa kaldır
if exist "%PROJECT_DIR%setup.sh" (
    del "%PROJECT_DIR%setup.sh"
    echo setup.sh dosyası kaldırıldı.
)

REM ZIP Arşivleme (PowerShell kullanarak)
echo Dosyaları ZIP arşivine sıkıştırılıyor...
powershell -Command "& {Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('%PROJECT_DIR%', '%PROJECT_ZIP%', 'Optimal', $false)}"

if %ERRORLEVEL% EQU 0 (
    echo ZIP arşivi başarıyla oluşturuldu: %PROJECT_ZIP%
) else (
    echo ZIP arşivi oluşturulurken bir hata oluştu!
)

echo.
echo ====================================================
echo Kurulum Tamamlandı!
echo ====================================================
echo.
echo Chrome Eklenti Kurulum Talimatları:
echo 1. Chrome tarayıcınızda 'chrome://extensions' adresine gidin
echo 2. Sağ üst köşedeki 'Geliştirici modu'nu etkinleştirin
echo 3. 'Paketlenmemiş öğe yükle' butonuna tıklayın
echo 4. Oluşturulan %PROJECT_DIR% klasörünü seçin
echo 5. Eklenti tarayıcınıza yüklenecektir
echo.
echo Alternatif olarak, oluşturulan %PROJECT_ZIP% dosyasını kullanabilirsiniz:
echo 1. ZIP dosyasını bir klasöre çıkarın
echo 2. Yukarıdaki 1-4 adımları uygulayın
echo.

pause